### ISSUE TITLE
Call Flow Wireframes

### ISSUE THREAD

**Issue by rubinovitz** [StayWokeOrg/general-congress-hotline#18]

**Comment by pascalpp** [comment]
FWIW I made a wireframe of a single call action:

![image](https://cloud.githubusercontent.com/assets/1355312/21780386/65235d50-d679-11e6-989b-b60be6af0f82.png)

once the user hears a prompt they'll enter other numbers into their phone (e.g. their zip code) and the cycle starts over again.

**Comment by pascalpp** [comment]
but yeah we need a wireframe of the whole call flow and the proposed changes.

**Comment by rubinovitz** [comment]
Posted this in wrong repo
